site_name: Ashe Wiki
site_url: https://ashe-wiki.github.io/
site_author: Ashe

repo_name: ashe-c0de/ashe-wiki
repo_url: https://github.com/ashe-c0de/ashe-wiki
edit_uri: edit/v1/docs/

copyright: Copyright &copy; 2024-Present <a href="https://github.com/ashe-c0de" target="_blank" rel="noopener noreferrer">Ashe</a>

theme:
  name: material
  language: en
  custom_dir: overrides

  favicon: assets/favicon.ico
  icon:
    logo: logo

  features:
    - header.autohide       # 启用头部自动隐藏
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
#    - navigation.sections
#    - navigation.expand
    - navigation.tabs
    - navigation.path
    - navigation.top
    - toc.follow
    - content.code.copy
    - content.action.edit
    - search.highlight

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
#  font:
#    text: Noto Serif SC
#    code: JetBrains Mono

plugins:
  - search:
      lang:
        - en
        - zh
  - glightbox

markdown_extensions:

  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.inlinehilite

  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

  - toc:
      permalink: true
  - pymdownx.tilde    


extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid-init.js

#extra_css:
#  - stylesheets/extra.css


nav:

  - Home: index.md

  - Lang:
      - Who am I: lang/index.md
      - Go:
          - "slice": lang/go/slice.md
          - "map": lang/go/map.md
          - "channel": lang/go/channel.md
          - "defer": lang/go/defer.md
          - "sync": lang/go/sync.md
          - "generics": lang/go/generics.md
          - "memory-escape": lang/go/memory-escape.md
          - "memory-leak": lang/go/memory-leak.md
          - "context": lang/go/context.md
          - "gmp": lang/go/gmp.md
          - "memory-allocator": lang/go/memory-allocator.md

      - Java:
          - env: lang/java/env.md
          - jvm memory structure: lang/java/jvm-memory-structure.md
          - Lambda表达式: lang/java/lambda.md
          - mvc: lang/java/mvc.md
          - Fixing Circular Dependencies in MyBatis-Plus: lang/java/di.md
      
      - Python:
          - env: lang/python/env.md
          - input-output: lang/python/input-output.md
          - variables: lang/python/variables.md

      - Rust:
          - Environment: lang/rust/environment.md
          - Declare-variables: lang/rust/declare-variables.md
          - Cargo: lang/rust/cargo.md
          - Data-type: lang/rust/data-type.md
          - Function: lang/rust/function.md
          - Control-flow: lang/rust/control-flow.md
          - Stack&heap: lang/rust/stack&heap.md
          - Ownership: lang/rust/ownership.md
          - Web: lang/rust/web.md
      - Markdown:
          - Grammar: lang/markdown/grammar.md
      - Git:
          - Grammar: lang/git/grammar.md
      - Design Pattern:
          - TODO: lang/dp/todo.md
          - Singleton: lang/dp/singleton.md
      - Data Structures and Algorithms:
          - Introduction to Big O Notation: lang/dsa/big-o.md
          - Two Pointer: lang/dsa/two-pointer.md
          - Expand Around Center: lang/dsa/expand-around-center.md
          - Manacher: lang/dsa/manacher.md
          - Sliding Window: lang/dsa/sliding-window.md
          - Prefix Sum: lang/dsa/prefix-sum.md


  - Database:
      - Bruce Lee: db/index.md
      - MySQL: 
          - index: db/mysql/ix.md
          - b+tree: db/mysql/b+tree.md
          - covering-index: db/mysql/covering-index.md
          - index-failure: db/mysql/index-failure.md
          - sql-flow: db/mysql/sql-flow.md
          - 脏读、不可重复读、幻读: db/mysql/dirty-read.md
          - mvcc: db/mysql/mvcc.md
          - join: db/mysql/join.md
          - slow query log: db/mysql/slow-query-log.md
      - Redis:
          - struct: db/redis/struct.md    
          - big key problem: db/redis/big-key-problem.md    
          - hot key problem: db/redis/hot-key-problem.md   
          - persistence-strategy: db/redis/persistence-strategy.md    
          - eviction-policy: db/redis/eviction-policy.md    
          - redis-cluster: db/redis/redis-cluster.md
      - Elasticsearch:
          - 安装Elasticsearch: db/elasticsearch/install.md
          - getting-started: db/elasticsearch/getting-started.md
          - 索引为yellow的解决方案: db/elasticsearch/yellow-index.md   
          - SpringBoot引入es启动失败: db/elasticsearch/sb-es.md   
          - 安装Kibana: db/elasticsearch/kibana.md   
          - ELK收集SpringBoot日志: db/elasticsearch/elk.md   

  - Infrastructure:
      - Unknown: infra/index.md
      - OS: 
          - Overview: infra/os/overview.md
          - Execution: infra/os/execution.md
          - Less: infra/os/less.md
      - Net:
          - Overview: infra/net/overview.md
          - Internet Layers: infra/net/il.md
          - RPC vs REST: infra/net/rpc.md
      - Hardware:
          - Touchpad: infra/hw/touchpad.md

  - Intelligence:
      - Buddha: ix/index.md
      - Agents:
          - opencode: ix/agents/opencode.md
      - Protocols: ix/protocols/todo.md
      - Models: ix/llm/todo.md

  - DevOps:
      - Longstreet: devops/index.md
      - Transactional-mq: devops/transactional-mq.md
      - Cache: devops/cache.md
      - Mq-loss: devops/mq-loss.md
      - Distributed-transaction: devops/distributed-transaction.md
      - Rate-limiting: devops/rate-limiting.md 
      - Distributed-lock: devops/distributed-lock.md 
      - Workflow: devops/workflow.md 
      - CentOS安装GitLab社区版: devops/gitlab.md 
      - GitLab社区版CI/CD实现: devops/gitlab-ci.md
       


  - Other:
      - Nietzsche: other/index.md
      - Tools: 
          - WezTerm + Neovim: other/tools/nvim.md
          - Scoop: other/tools/scoop.md
          - ssh gui: other/tools/ssh-gui.md
          - Visual Studio Code: other/tools/vscode.md
