name: Deploy Ashe Wiki

on:
  push:
    branches:
      - v1

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the wiki repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # 3. Install MkDocs and Material theme
      - name: Install MkDocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
          pip install mkdocs-glightbox

      # 3.1 Update Copyright Year
      - name: Update Copyright Year
        run: |
          sed -i "s/{{YEAR}}/$(date +%Y)/" mkdocs.yml

      # 4. Build the static site
      - name: Build site
        run: mkdocs build --clean --site-dir site

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
          repository-name: ashe-wiki/ashe-wiki.github.io
          branch: main
          folder: site
          clean: true
          clean-exclude: |
            25/